# This file was generated by GoReleaser. DO NOT EDIT.
cask "appstorys-cli" do
  name "appstorys-cli"
  desc "Finds, checks and fixes AppStorys SDK instrumentation in a mobile app"
  homepage "https://github.com/appversal/appstorys-cli"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "appstorys-cli"

  on_macos do
    on_intel do
      url "https://github.com/appversal/appstorys-cli/releases/download/v#{version}/appstorys-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "8efa11b1aefa2a99b6a50eb062af04e285a84e4b511a52f91caa4d5276f95ae3"
    end
    on_arm do
      url "https://github.com/appversal/appstorys-cli/releases/download/v#{version}/appstorys-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "822cac4a5a862583002955fc94a0a6d86b470713368ae996872d239ce4ef65ba"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/appversal/appstorys-cli/releases/download/v#{version}/appstorys-cli_#{version}_linux_amd64.tar.gz"
      sha256 "21be5ffbb4f171e165e81782bc659f6c2a8778a00e3ca764a36247e390cce0a5"
    end
    on_arm do
      url "https://github.com/appversal/appstorys-cli/releases/download/v#{version}/appstorys-cli_#{version}_linux_arm64.tar.gz"
      sha256 "1df82cdfec159aaf891af60580b4e8af6618f6affbd3312992d2f48c1fd857ef"
    end
  end

  # No zap stanza required
end
